### ISSUE TITLE
`ClientSession.close` deprecated when called directly via run_until_complete(2.2.3)

### ISSUE THREAD

**Issue by litwisha** [aio-libs/aiohttp#2065]
## Long story short

When you close session directly via `loop.run_until_complete(session.close())`, it is deprecated.
The reason is that `_CoroGuard` inherits from `_BaseCoroMixin` that inherits from `collections.abc.Coroutine`.
 https://github.com/aio-libs/aiohttp/blob/v2.2.3/aiohttp/helpers.py#L108
And when calling `loop.run_until_complete(session.close())` then `__await__` or `__iter__` methods are unreachable, `send` method is called instead. That's why, `self._awaited` attribute is not changed to `True`.

## Expected behaviour
Direct closing `loop.run_until_complete(session.close())` is not deprecated

## Actual behaviour

Direct closing `loop.run_until_complete(session.close())` is deprecated

## Steps to reproduce

```python
import asyncio  
from aiohttp import ClientSession

loop = asyncio.get_event_loop()

session = ClientSession(loop=loop)
loop.run_until_complete(session.close())
```

## Your environment

```
OS X 10.12.3
python 3.6.0
aiohttp==2.2.3
```

**Comment by asvetlov** [comment]
I pretty sure the issue is fixed by 97db67bf and e176536d.
https://github.com/aio-libs/aiohttp/blob/master/tests/test_client_session.py#L58-L60 test is finished without any warning

**Comment by litwisha** [comment]
@asvetlov 
no, it is not fixed for py35+.
Here is a negative test for it.
https://github.com/aio-libs/aiohttp/pull/2077

**Comment by litwisha** [comment]
@asvetlov 
any ideas?

**Comment by asvetlov** [comment]
Sure :)
This weekend I'll lead a sprint, hope to find a time for making fix.

**Comment by asvetlov** [comment]
Fixed by @2161
Released in aiohttp 2.2.5
