### ISSUE TITLE
EofStream and autoclose

### ISSUE THREAD

**Issue by thomaszdxsn** [aio-libs/aiohttp#2784]
## Long story short

Hi, I meet a problem with websocket's client message, sometimes I will receive EofStream object instead of bytes or str(so broken my program).I don't now what's this object.But I guess it means EOF right?

```python
async for msg in self._ws_conn:
    msg_data = json.loads(msg_data)  # msg_data maybe EofStream
```

## Expected behaviour

If EofStream meaning EOF, Why not just close this websocket connection, beacuase I see `ws_connect()` have a argument named 'autoclose', it default to `True`?

Or EofStream has other meaning?

**Comment by asvetlov** [comment]
Is it aiohttp 3.0?

**Comment by thomaszdxsn** [comment]
"version": "==3.0.6"

It's my pipfile.lock's content

**Comment by asvetlov** [comment]
This is a bug, iteration over websocket messages should be stopped without returning stop marker to user.
Would you work on bugfix?

**Comment by thomaszdxsn** [comment]
yeah, i should take time to read contribute guide

**Comment by asvetlov** [comment]
Fixed by #2814, released by aiohttp 3.1

**Comment by socketpair** [comment]
Seems still actual. `await websocket.receive_json() # Will die with TypeError on WSMsgType.CLOSED`

**Comment by socketpair** [comment]
aiohttp 3.8.1

`await websocket.receive_json()` Will die with `TypeError` on `WSMsgType.CLOSED`.

```python
 async def __anext__(self) -> WSMessage:
        msg = await self.receive()
        if msg.type in (WSMsgType.CLOSE, WSMsgType.CLOSING, WSMsgType.CLOSED):
            raise StopAsyncIteration
        return msg
```

Yes, bug is fixed in iterator but NOT fixed for `websocket.receive_*` functions, like `receive_json()`

I would raise RuntimeError or so if corresponding message "type" (like bytes, str, or json) can not be received.

**Comment by socketpair** [comment]
see #6800
