### ISSUE TITLE
Wrong type hint for tracing Signal sequence

### ISSUE THREAD

**Issue by stj** [aio-libs/aiohttp#3595]
## Long story short

Type hints for tracing Signal contents look wrong.

## Expected behaviour

mypy does not report an error when adding handlers to a signal object.

## Actual behaviour

mypy reports an error of
```bash
error: List item 0 has incompatible type "Callable[[ClientSession, SimpleNamespace, TraceConnectionCreateEndParams], Coroutine[Any, Any, None]]"; expected "Callable[[TraceConfig], Awaitable[None]]"
```

## Steps to reproduce

Run mypy over this snippet
```python
import types

import aiohttp
import datadog

async def reuse_keepalive_connection(
    session: aiohttp.ClientSession,
    trace_config_ctx: types.SimpleNamespace,
    params: aiohttp.TraceConnectionReuseconnParams,
) -> None:
    """statsd counter; how often has a connection been reused"""
    datadog.statsd.increment("client.request.connection.reuse")

tracer = aiohttp.TraceConfig()
tracer.on_connection_reuseconn.extend([reuse_keepalive_connection])
```

## Your environment

aiohttp 3.5.4
python 3.7.2
mypy 0.660

**Comment by asvetlov** [comment]
Fixed by #3596

**Comment by 0xD09CD196D188D0B0** [comment]
The similar issue still appears for me:
```
class RequestLogger:
    async def _on_request_start(
        self,
        session: aiohttp.ClientSession,
        context: SimpleNamespace,
        params: aiohttp.TraceRequestStartParams,
    ) -> None:
        ...

    def make_trace_config(self):
        tc = aiohttp.TraceConfig()
        tc.on_request_start.append(self._on_request_start)
        return tc
```
results with:
```
 error: Argument 1 to "append" of "MutableSequence" has incompatible type "Callable[[ClientSession, SimpleNamespace, TraceRequestStartParams], Coroutine[Any, Any, None]]"; expected "Callable[[ClientSession, SimpleNamespace, <union: 15 items>], Awaitable[None]]"
```

Python 3.7.7
mypy 0.770

**Comment by asvetlov** [comment]
type annotation is reimplemented
