### ISSUE TITLE
Failed building wheel for aiohttp on Python 3.5.0rc1

### ISSUE THREAD

**Issue by playpauseandstop** [aio-libs/aiohttp#467]
Got,

```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/fp/j7wp2x1571q6srvmfvksq_k80000gn/T/pip-build-wdizzg6y/aiohttp/setup.py", line 93, in <module>
      setup(**args)
    File "/Users/playpauseandstop/.pyenv/versions/3.5.0rc1/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/playpauseandstop/.pyenv/versions/3.5.0rc1/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Users/playpauseandstop/.pyenv/versions/3.5.0rc1/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/playpauseandstop/Projects/.../env/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 213, in run
      archive_basename = self.get_archive_basename()
    File "/Users/playpauseandstop/Projects/.../env/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 161, in get_archive_basename
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/Users/playpauseandstop/Projects/.../env/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 155, in get_tag
      assert tag == supported_tags[0]
  AssertionError

  ----------------------------------------
  Failed building wheel for aiohttp
```

while installing `aiothttp==0.17.2` on Python 3.5.0rc1. 

So proposed to add new classifier for `aiohttp`, that it supports Python 3.5

**Comment by asvetlov** [comment]
Done for master and 0.17 branch (no aiohttp 0.17.3 release yet)

**Comment by playpauseandstop** [comment]
Unfortunatelly that is not aiohttp, but wheel issue. Version 0.17.3 with proper platform tag still not building wheel cause of https://bitbucket.org/pypa/wheel/issues/146/wheel-building-fails-on-cpython-350b3
