### ISSUE TITLE
Any media type starting with application/json treated as JSON

### ISSUE THREAD

**Issue by scop** [aio-libs/aiohttp#5896]
### Describe the bug

Any media type that starts with `application/json` is treated as JSON. This treatment should be limited to `application/json` and types with `+json` media type suffix. An example of a registered media type that triggers this problem is https://www.iana.org/assignments/media-types/application/json-seq

### To Reproduce

PR #5895 has a failing test case.

### Expected behavior

Not anything that begins with `application/json` should be treated as JSON.

### Logs/tracebacks

```python-traceback
-
```

### Python Version

```console
$ python --version
Python 3.9.6
```

### aiohttp Version

```console
$ python -m pip show aiohttp
WARNING: Package(s) not found: aiohttp

(current git master)
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.1.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/scop/.pyenv/versions/3.9.6/envs/aiohttp/lib/python3.9/site-packages
Requires: 
Required-by: yarl
```

### yarl Version

```console
$ python -m pip show yarl
Version: 1.6.3
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/scop/.pyenv/versions/3.9.6/envs/aiohttp/lib/python3.9/site-packages
Requires: multidict, idna
Required-by:
```

### OS

Any

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by asvetlov** [comment]
Fixed by #5894

**Comment by scop** [comment]
As mentioned in https://github.com/aio-libs/aiohttp/pull/5895#issuecomment-950321559, this is a different thing, not fixed by #5894. The test case in #5895 still fails.

**Comment by scop** [comment]
Real fix in #6180.
